### ISSUE TITLE
How to migerate data?

### ISSUE THREAD

**Issue by izayoi-akira** [bitnami/bitnami-docker-etcd#19]
some data on the local server,I want to migerate  then to an other server
then I tried : 
1. copy the dir /etcd_data to new server
2. only copy  /etcd_data/member/snap/db file to new server
3. local server exec  etcdctl  snapshot save and  other server exec etcdctl snapshot restore
none of them worked

**Comment by izayoi-akira** [comment]
> some data on the local server,I want to migerate then to an other server
> then I tried :
> 
> 1. copy the dir /etcd_data to new server
> 2. only copy  /etcd_data/member/snap/db file to new server
> 3. local server exec  etcdctl  snapshot save and  other server exec etcdctl snapshot restore
>    none of them worked

when I use etcdctl snapshot restore like this:
`etcdctl snapshot restore snapshot.db --data-dir=/etcd_data`
it error with: `Error: data-dir "/etcd_data" exists`
then change the data-dir:
`etcdctl snapshot restore snapshot.db --data-dir=/etcd_data_new`
error with: `Error: mkdir /etcd_data_new: permission denied`

**Comment by javsalgar** [comment]
Hi,

Did you try ectdctl snapshot save? Documentation from the official etcd project here https://support.coreos.com/hc/en-us/articles/115000323894-Creating-etcd-backup
