### ISSUE TITLE
A Restart Pod may be permantly removed from cluster

### ISSUE THREAD

**Issue by haorenfsa** [bitnami/bitnami-docker-etcd#27]
**Description**

A Restart Pod may be permantly removed from cluster. This is because the `prestop.sh` script is not atomic when remove itself from cluster & write `member_removal.log`.

see prestop.sh:

``` sh
etcdctl member remove "$(cat "${ETCD_DATA_DIR}/member_id")" "${extra_flags[@]}" > "$(dirname "$ETCD_DATA_DIR")/member_removal.log"
```

Due to network or other problem, the leader may already removed the `member_id`, but the node running `prestop.sh` doesn't receive the result.

**Steps to reproduce the issue:**

1. use helm chart to create etcd cluster with 3 nodes
2. use some traffic trick like `tc` to make lantency long
3. delete the stateful set with --cascade=orphan
4. save a follower node's manifest
5. delete the follower node
6. delete the `tc` rule, to make lantency normal
7. start the follower node again

**Describe the results you received:**

The restarted follower doesn't leave a correct removal log before exit, so it restart with old `member_id`, which is already permantly removed from cluster.

**Describe the results you expected:**

The restarted follower should check if the old `member_id` is removed from cluster, and use a new member_id if needed.

**Additional information you deem important (e.g. issue happens only occasionally):**

image version:  `3.5.0-debian-10-r24`

**Comment by haorenfsa** [comment]
Possible Solution:

We may write removal log both before & after calling remove, and call remove again when we found only before removal log to make sure remove succeeded.

**Comment by haorenfsa** [comment]
Flush memory may solve the problem in most situations, but there's still chances we fail to write file when extreme things happens. Hopes we can find a better solution.

**Comment by alemorcuq** [comment]
Sorry for the delay, we lost track of this ticket. A colleague will review your PR, thank you very much for the contribution.
