### ISSUE TITLE
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

### ISSUE THREAD

**Issue by lookhua** [bitnami/bitnami-docker-etcd#29]
**Description**

**Steps to reproduce the issue:**

1. deploy etcd in k8s version 20.0 and set replicate = 3 
2. scale the replicate to 5 
3.  then the pod restart fail ,the log message bellow:
[38;5;6metcd [38;5;5m06:16:20.84 [0m
[38;5;6metcd [38;5;5m06:16:20.84 [0m[1mWelcome to the Bitnami etcd container[0m
[38;5;6metcd [38;5;5m06:16:20.84 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-etcd[0m
[38;5;6metcd [38;5;5m06:16:20.84 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-etcd/issues[0m
[38;5;6metcd [38;5;5m06:16:20.84 [0m
[38;5;6metcd [38;5;5m06:16:20.84 [0m[38;5;2mINFO [0m ==> ** Starting etcd setup **
[38;5;6metcd [38;5;5m06:16:20.86 [0m[38;5;2mINFO [0m ==> Validating settings in ETCD_* env vars..
[38;5;6metcd [38;5;5m06:16:20.86 [0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
[38;5;6metcd [38;5;5m06:16:20.86 [0m[38;5;2mINFO [0m ==> Initializing etcd
[38;5;6metcd [38;5;5m06:16:20.87 [0m[38;5;2mINFO [0m ==> Detected data from previous deployments
[38;5;6metcd [38;5;5m06:16:30.97 [0m[38;5;2mINFO [0m ==> Updating member in existing cluster
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Could you specify the exact instructions you used for deploying and scaling the cluster?
