### ISSUE TITLE
Add arm64 multi-arch image support for etcd

### ISSUE THREAD

**Issue by xin3liang** [bitnami/bitnami-docker-etcd#32]
There is no arm64 image in the [release image repo](https://hub.docker.com/r/bitnami/etcd/tags) yet. Can we built and push multi-arch images in there?
BTW, [minideb ](https://hub.docker.com/r/bitnami/minideb/tags) provides arm64 image already.

**Comment by juan131** [comment]
Closing as duplicate of https://github.com/bitnami/charts/issues/7305
