### ISSUE TITLE
feature: support add `--insecure-skip-tls-verify` in health check

### ISSUE THREAD

**Issue by starsz** [bitnami/bitnami-docker-etcd#35]
**Description**

**Steps to reproduce the issue:**

Hi, I found that we don't support adding `--insecure-skip-tls-verify` in health check.
I think it's useful if we use our own SSL key and certs.
So I just want to know can we support this function. And we can both support it in the helm chart.
I can do some contributions to this feature.

Looking forward to your reply, thank you very much.

**Describe the results you received:**

**Describe the results you expected:**

And an option to control whether add `--insecure-skip-tls-verify` flag in health check.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

**Comment by carrodher** [comment]
Thanks for the suggestion, sure, feel free to create a PR and the team will be happy to provide feedback!

**Comment by starsz** [comment]
> Thanks for the suggestion, sure, feel free to create a PR and the team will be happy to provide feedback!

Haha. Let me create a PR. 😄
