### ISSUE TITLE
docker-compose cluster restart failed

### ISSUE THREAD

**Issue by PixelByProxy** [bitnami/bitnami-docker-etcd#36]
I'm able to start the cluster but when I try to re-start a node it fails with the error below.

**Steps to reproduce the issue:**

1. Use the docker-compose-cluster.yml in this repo 
2. Start the cluster with docker-compose up -d
3. Re-start a node (eg: docker restart etcd2)

**Describe the results you received:**

```md
etcd 22:09:59.01 
etcd 22:09:59.01 Welcome to the Bitnami etcd container
etcd 22:09:59.01 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 22:09:59.02 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 22:09:59.02 
etcd 22:09:59.02 INFO  ==> ** Starting etcd setup **
etcd 22:09:59.03 INFO  ==> Validating settings in ETCD_* env vars..
etcd 22:09:59.03 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 22:09:59.04 INFO  ==> Initializing etcd
etcd 22:09:59.04 INFO  ==> Generating etcd config file using env variables
etcd 22:09:59.05 INFO  ==> Detected data from previous deployments
etcd 22:09:59.06 INFO  ==> Updating member in existing cluster
{"level":"warn","ts":"2022-01-14T22:10:04.094Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000164700/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
```

**Describe the results you expected:**

Restart should succeed.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

Docker Version Info:

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by carrodher** [comment]
In order to debug the issue, I added the `BITNAMI_DEBUG=true` environment variable to the 3 containers.
Then, I deployed the cluster by running
```console
$ docker-compose up -d
...
etcd3_1  | etcd 07:24:26.41 DEBUG ==> Stored member ID: bd388e7810915853
etcd2_1  | etcd 07:24:27.53 DEBUG ==> Stored member ID: d282ac2ce600c1ce
etcd1_1  | etcd 07:24:28.51 DEBUG ==> Stored member ID: ade526d28b1f92f7

$ docker ps
CONTAINER ID   IMAGE            COMMAND                  CREATED              STATUS              PORTS           NAMES
e8f0e0adbf20   bitnami/etcd:3   "/opt/bitnami/script…"   About a minute ago   Up About a minute   2379-2380/tcp   bitnami-docker-etcd_etcd1_1
55bb0db7ca1f   bitnami/etcd:3   "/opt/bitnami/script…"   About a minute ago   Up About a minute   2379-2380/tcp   bitnami-docker-etcd_etcd2_1
b5eba79b76e3   bitnami/etcd:3   "/opt/bitnami/script…"   About a minute ago   Up About a minute   2379-2380/tcp   bitnami-docker-etcd_etcd3_1
```

In order to reproduce the issue, I restarted the second node by running
```
$ docker restart bitnami-docker-etcd_etcd2_1
bitnami-docker-etcd_etcd2_1
```

The container was restarted, but as you rightly said, the initialization is not being completed:
```
etcd2_1  | etcd 07:26:48.27 INFO  ==> Validating settings in ETCD_* env vars..
etcd2_1  | etcd 07:26:48.27 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd2_1  | etcd 07:26:48.28 INFO  ==> Initializing etcd
etcd2_1  | etcd 07:26:48.28 INFO  ==> Generating etcd config file using env variables
etcd2_1  | etcd 07:26:48.29 INFO  ==> Detected data from previous deployments
etcd2_1  | etcd 07:26:48.29 DEBUG ==> Setting data directory permissions to 700 in a recursive way (required in etcd >=3.4.10)
etcd2_1  | chmod: changing permissions of '/bitnami/etcd/data': Operation not permitted
etcd2_1  | etcd 07:26:48.30 INFO  ==> Updating member in existing cluster
etcd2_1  | {"level":"warn","ts":"2022-01-17T07:26:53.336Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000374700/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
etcd2_1  | Error: context deadline exceeded
bitnami-docker-etcd_etcd2_1 exited with code 1
```

Now, thanks to the debug we can see an issue trying to change the permissions of the volume which doesn't appear in the regular initialization:
```
etcd2_1  | etcd 07:26:48.29 INFO  ==> Detected data from previous deployments
etcd2_1  | etcd 07:26:48.29 DEBUG ==> Setting data directory permissions to 700 in a recursive way (required in etcd >=3.4.10)
etcd2_1  | chmod: changing permissions of '/bitnami/etcd/data': Operation not permitted
```

I was not able to reproduce the issue if restarting the whole cluster at the same time, so it seems the issue only appears when restarting one of the members. According to the logs messages, the logic which is failing is 

https://github.com/bitnami/bitnami-docker-etcd/blob/0d811fb5fd6704324de58952c430dcac8d37aade/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L626

I'm going to create an internal task for this issue, although due to the issue is affecting docker-compose and not Helm chart (which is what we consider production-ready deployable artifact), I can't provide any ETA for this task, it would depend on the different priorities the team has.
In the meantime, as all the code is publicly available in this repo we would be happy to review any PR addressing the issue if you would like to contribute.

**Comment by XiaoYang1127** [comment]
I also encountered this problem until I lowered ETCD to 3.4.4 in docker-compose


version: "3"
networks:
  net_etcd_cluster:

services:
  etcd1:
    image: bitnami/etcd:3.4.4
    container_name: etcd1
    ports:
      - "23800:2380"
      - "23790:2379"
    environment:
      - ETCD_DEBUG=True
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23790
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd1:/bitnami/etcd
    networks:
      - net_etcd_cluster

  etcd2:
    image: bitnami/etcd:3.4.4
    container_name: etcd2
    ports:
      - "23801:2380"
      - "23791:2379"
    environment:
      - ETCD_DEBUG=True
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23791
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd2:/bitnami/etcd
    networks:
      - net_etcd_cluster

  etcd3:
    image: bitnami/etcd:3.4.4
    container_name: etcd3
    ports:
      - "23802:2380"
      - "23792:2379"
    environment:
      - ETCD_DEBUG=True
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23792
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd3:/bitnami/etcd
    networks:
      - net_etcd_cluster

  etcdkeeper:
    image: deltaprojects/etcdkeeper
    container_name: etcdkeeper
    ports:
      - 8088:8080
    networks:
      - net_etcd_cluster

**Comment by XiaoYang1127** [comment]
I also encountered this problem until I lowered the ETCD from 3.5.2 to 3.4.4
Here is my docker-compose configuration

`version: "3"
networks:
  net_etcd_cluster:

services:
  etcd1:
    image: bitnami/etcd:3.4.4
    container_name: etcd1
    ports:
      - "23800:2380"
      - "23790:2379"
    environment:
      - ETCD_DEBUG=True
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23790
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd1:/bitnami/etcd
    networks:
      - net_etcd_cluster

  etcd2:
    image: bitnami/etcd:3.4.4
    container_name: etcd2
    ports:
      - "23801:2380"
      - "23791:2379"
    environment:
      - ETCD_DEBUG=True
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23791
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd2:/bitnami/etcd
    networks:
      - net_etcd_cluster

  etcd3:
    image: bitnami/etcd:3.4.4
    container_name: etcd3
    ports:
      - "23802:2380"
      - "23792:2379"
    environment:
      - ETCD_DEBUG=True
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23792
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd3:/bitnami/etcd
    networks:
      - net_etcd_cluster

  etcdkeeper:
    image: deltaprojects/etcdkeeper
    container_name: etcdkeeper
    ports:
      - 8088:8080
    networks:
      - net_etcd_cluster
`

**Comment by DarthPestilane** [comment]
same here, using `bitnami/etcd:3.5`

**Comment by carrodher** [comment]
There is an internal task created for this issue, although due to the issue is affecting docker-compose and not Helm chart (which is what we consider production-ready deployable artifact), I can't provide any ETA for this task, it would depend on the different priorities the team has.

In the meantime, as all the code is publicly available in this repo we would be happy to review any PR addressing the issue if you would like to contribute.

**Comment by Yullin** [comment]
Version 3.5.1 and 3.5.2, Got following issue with docker-compose
'''
etcd 19:38:03.66
etcd 19:38:03.66 Welcome to the Bitnami etcd container
etcd 19:38:03.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 19:38:03.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 19:38:03.66
etcd 19:38:03.66 INFO  ==> ** Starting etcd setup **
etcd 19:38:03.68 INFO  ==> Validating settings in ETCD_* env vars..
etcd 19:38:03.68 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 19:38:03.68 INFO  ==> Initializing etcd
etcd 19:38:03.68 INFO  ==> Generating etcd config file using env variables
chown: cannot access '/opt/bitnami/etcd/conf/etcd.yaml': No such file or directory
'''

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
