### ISSUE TITLE
Cluster ID Mismatch When start a new etcd-cluster

### ISSUE THREAD

**Issue by haorenfsa** [bitnami/bitnami-docker-etcd#45]
### Name and Version

bitnami/etcd:3.5.0

### What steps will reproduce the bug?

Deploy the etcd helm-chart multiple times. It happens about once out of 10 times in our Kubernetes cluster.
It seems more likely to reproduce in a high-load cluster.

### What is the expected behavior?

The etcd cluster always starts successfully.

### What do you see instead?

Sometimes some nodes can never start.
And we see logs in the fail nodes like this:

```
"level":"warn","ts":"2022-05-30T03:25:22.307Z","caller":"rafthttp/http.go:500","msg":"request cluster ID mismatch","local-member-id":"5b123476293d2113","local-member-cluster-id":"9a5261f0f5bb77d","local-member-server-version":"3.5.0","local-member-server-minimum-cluster-version":"3.0.0","remote-peer-server-name":"4dcd331e807294f0","remote-peer-server-version":"3.5.0","remote-peer-server-minimum-cluster-version":"3.0.0","remote-peer-cluster-id":"fc8c9db6d2887a92"}
```

### Additional information

When first time startup, the `ETCD_INITIAL_CLUSTER` is initialized by `recalculate_initial_cluster()` which uses `etcdctl_get_endpoints()`. And the `etcdctl_get_endpoints()` uses `getent ahost` to find all entrypoints from `DNS` server by the `headless service` hostname.

While in Kubernetes, if a statefulset multiple pods, which means the `headless service` has multiple DNS `A record`, the `headless service` `A records` will not be added to `DNS` atomically.  So when we run `getent ahost` for a new 3 node etcd cluster, maybe only 1 or 2 out of all 3 `A records` are added.

This means there're chances that `ETCD_INITIAL_CLUSTER` may return only part of the etcd entrypoints. An etcd node calculates its `Cluster ID` though all `Member IDs` it knows from `ETCD_INITIAL_CLUSTER`, so it may generate a `wrong` `Cluster ID`. And once the etcd node started, the calculated `Cluster ID` is written into `WAL`, and will never be able to change it unless we delete the `WAL`.

Solution: We should not use `recalculate_initial_cluster()` when a new cluster's nodes first time starts. Instead, we should use the original `ETCD_INITIAL_CLUSTER`

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will review it and provide feedback
