### ISSUE TITLE
Upgrading issue when upgrade current release to use no prestop feature

### ISSUE THREAD

**Issue by haorenfsa** [bitnami/bitnami-docker-etcd#46]
### Name and Version

bitnami/etcd:latest

### What steps will reproduce the bug?

- Install a release without setting ETCD_DISABLE_PRESTOP
- upgrade the release set ETCD_DISABLE_PRESTOP=true

### What is the expected behavior?

The etcd cluster upgrades successfully

### What do you see instead?

Nodes fails to rejoin the cluster since they're removed by the previous prestop hook

### Additional information

This is a follow up of patch #42

**Comment by haorenfsa** [comment]
I'm trying to fix it so that those who're using former versions can switch to new.

**Comment by dgomezleon** [comment]
Hi @haorenfsa ,

Thanks for all your contributions. 

I can see you have 2 open PR. The team will review them soon.

**Comment by haorenfsa** [comment]
#49

**Comment by dgomezleon** [comment]
Thanks for sharing it and for your contributions @haorenfsa ,

The issue has been closed after merging both PRs. If you think otherwise, please let us know.
