### ISSUE TITLE
ARS   System risk report   (High level vulnerability)

### ISSUE THREAD

**Issue by miaomiaomao1** [bitnami/bitnami-docker-etcd#48]
### Name and Version

bitnami/etcd:3.4.15              

### What steps will reproduce the bug?

ETCD REST API未授权访问漏洞【原理检测】
etcd是CoreOS团队于2013年6月发起的开源项目，它的目标是构建一个高可用的分布式键值(key-value)数据库。etcd内部采用raft协议作为一致性算法，etcd基于G
o语言实现。其API接口没有正确配置的话，将导致未授权访问漏洞
Etcd rest API unauthorized access vulnerability [principle detection]

Etcd is an open source project initiated by the coreos team in june2013. Its goal is to build a highly available distributed key value database. The raft protocol is used as the consistency algorithm in etcd, and etcd is based on G

O language implementation. If its API interface is not configured correctly, it will lead to unauthorized access vulnerability

BUG url for  http://xxx.xxx.xx.xxxx:2379/v2/keys/ 

### What is the expected behavior?

ETCD REST API未授权访问漏洞【原理检测】
etcd是CoreOS团队于2013年6月发起的开源项目，它的目标是构建一个高可用的分布式键值(key-value)数据库。etcd内部采用raft协议作为一致性算法，etcd基于G
o语言实现。其API接口没有正确配置的话，将导致未授权访问漏洞
Etcd rest API unauthorized access vulnerability [principle detection]

Etcd is an open source project initiated by the coreos team in june2013. Its goal is to build a highly available distributed key value database. The raft protocol is used as the consistency algorithm in etcd, and etcd is based on G

O language implementation. If its API interface is not configured correctly, it will lead to unauthorized access vulnerability

BUG url for  http://xxx.xxx.xx.xxxx:2379/v2/keys/ 

### What do you see instead?

ETCD REST API未授权访问漏洞【原理检测】
etcd是CoreOS团队于2013年6月发起的开源项目，它的目标是构建一个高可用的分布式键值(key-value)数据库。etcd内部采用raft协议作为一致性算法，etcd基于G
o语言实现。其API接口没有正确配置的话，将导致未授权访问漏洞
Etcd rest API unauthorized access vulnerability [principle detection]

Etcd is an open source project initiated by the coreos team in june2013. Its goal is to build a highly available distributed key value database. The raft protocol is used as the consistency algorithm in etcd, and etcd is based on G

O language implementation. If its API interface is not configured correctly, it will lead to unauthorized access vulnerability

BUG url for  http://xxx.xxx.xx.xxxx:2379/v2/keys/ 

### Additional information

So, what can we do to avoid this high-risk vulnerability

**Comment by rafariossaa** [comment]
Hi,
  I am not sure what is this issue about.
  Could you elaborate a bit ?
