### ISSUE TITLE
Will etcd chart support arm64 arch?

### ISSUE THREAD

**Issue by cwocwo** [bitnami/bitnami-docker-etcd#6]
**Description**

We want to use etcd on arm64 arch.
Will etcd chart support arm64 arch?

**Comment by rafariossaa** [comment]
Hi @cwocwo ,
  I am sorry to tell you that for now we are not creating docker images for that architecture.

Best regards,

**Comment by cwocwo** [comment]
Could you give some suggestions or method that we can build the image ourself?

**Comment by beltran-rubo** [comment]
Bitnami containers do not support the arm64 architecture. 

There is not a simple way to support it. A possible way is to build the container on your own: get a Debian or any distro that supports arm64 and you can download the binaries for arm64 from https://github.com/etcd-io/etcd/releases Then would be required to configure it, but that is basically building the container from scratch.

**Comment by cwocwo** [comment]
@beltran-rubo Thanks for your reply. We have already build the arm64 image, but it is different with bitnami's image, it can't ran properly with the bitnami etcd chat. Any ideas?

**Comment by rafariossaa** [comment]
Hi @cwocwo ,
  Which problem are you facing ?
