### ISSUE TITLE
docker build link

### ISSUE THREAD

**Issue by lanartri** [bitnami/bitnami-docker-etcd#9]
Not a big deal, just noticed that link at README is for your other repo,

`$ docker build -t bitnami/etcd:latest 'https://github.com/bitnami/bitnami-docker-nginx.git#master:3/debian-10'`

**Comment by carrodher** [comment]
Hi! Thanks for letting us know, I just fixed it in this commit https://github.com/bitnami/bitnami-docker-etcd/commit/129d85b99ca9386cb4c7a9df7e8cb78816c1034e
